// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: {{cookiecutter.module_name}}/v1/{{cookiecutter.module_name}}.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_{{cookiecutter.module_name}}_v1_{{cookiecutter.module_name}}_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_{{cookiecutter.module_name}}_v1_{{cookiecutter.module_name}}_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_{{cookiecutter.module_name}}_v1_{{cookiecutter.module_name}}_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_{{cookiecutter.module_name}}_v1_{{cookiecutter.module_name}}_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_{{cookiecutter.module_name}}_v1_{{cookiecutter.module_name}}_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_{{cookiecutter.module_name}}_v1_{{cookiecutter.module_name}}_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_{{cookiecutter.module_name}}_v1_{{cookiecutter.module_name}}_proto protoreflect.FileDescriptor

const file_{{cookiecutter.module_name}}_v1_{{cookiecutter.module_name}}_proto_rawDesc = "" +
	"\n" +
	"\x1e{{cookiecutter.module_name}}/v1/{{cookiecutter.module_name}}.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2l\n" +
	"\n" +
	"{{cookiecutter.module_name}}\x12^\n" +
	"\bSayHello\x12\x1b.helloworld.v1.HelloRequest\x1a\x19.helloworld.v1.HelloReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/{{cookiecutter.module_name}}/{name}BT\n" +
	"\x1cdev.kratos.api.{{cookiecutter.module_name}}.v1B\x11HelloworldProtoV1P\x01Z\x1f{{cookiecutter.module_name}}/api/{{cookiecutter.module_name}}/v1;v1b\x06proto3"

var (
	file_{{cookiecutter.module_name}}_v1_{{cookiecutter.module_name}}_proto_rawDescOnce sync.Once
	file_{{cookiecutter.module_name}}_v1_{{cookiecutter.module_name}}_proto_rawDescData []byte
)

func file_{{cookiecutter.module_name}}_v1_{{cookiecutter.module_name}}_proto_rawDescGZIP() []byte {
	file_{{cookiecutter.module_name}}_v1_{{cookiecutter.module_name}}_proto_rawDescOnce.Do(func() {
		file_{{cookiecutter.module_name}}_v1_{{cookiecutter.module_name}}_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_{{cookiecutter.module_name}}_v1_{{cookiecutter.module_name}}_proto_rawDesc), len(file_{{cookiecutter.module_name}}_v1_{{cookiecutter.module_name}}_proto_rawDesc)))
	})
	return file_{{cookiecutter.module_name}}_v1_{{cookiecutter.module_name}}_proto_rawDescData
}

var file_{{cookiecutter.module_name}}_v1_{{cookiecutter.module_name}}_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_{{cookiecutter.module_name}}_v1_{{cookiecutter.module_name}}_proto_goTypes = []any{
	(*HelloRequest)(nil), // 0: helloworld.v1.HelloRequest
	(*HelloReply)(nil),   // 1: helloworld.v1.HelloReply
}
var file_{{cookiecutter.module_name}}_v1_{{cookiecutter.module_name}}_proto_depIdxs = []int32{
	0, // 0: helloworld.v1.{{cookiecutter.module_name}}.SayHello:input_type -> helloworld.v1.HelloRequest
	1, // 1: helloworld.v1.{{cookiecutter.module_name}}.SayHello:output_type -> helloworld.v1.HelloReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_{{cookiecutter.module_name}}_v1_{{cookiecutter.module_name}}_proto_init() }
func file_{{cookiecutter.module_name}}_v1_{{cookiecutter.module_name}}_proto_init() {
	if File_{{cookiecutter.module_name}}_v1_{{cookiecutter.module_name}}_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_{{cookiecutter.module_name}}_v1_{{cookiecutter.module_name}}_proto_rawDesc), len(file_{{cookiecutter.module_name}}_v1_{{cookiecutter.module_name}}_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_{{cookiecutter.module_name}}_v1_{{cookiecutter.module_name}}_proto_goTypes,
		DependencyIndexes: file_{{cookiecutter.module_name}}_v1_{{cookiecutter.module_name}}_proto_depIdxs,
		MessageInfos:      file_{{cookiecutter.module_name}}_v1_{{cookiecutter.module_name}}_proto_msgTypes,
	}.Build()
	File_{{cookiecutter.module_name}}_v1_{{cookiecutter.module_name}}_proto = out.File
	file_{{cookiecutter.module_name}}_v1_{{cookiecutter.module_name}}_proto_goTypes = nil
	file_{{cookiecutter.module_name}}_v1_{{cookiecutter.module_name}}_proto_depIdxs = nil
}
