// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: {{cookiecutter.module_name}}/v1/{{cookiecutter.module_name}}.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	{{cookiecutter.module_name}}_SayHello_FullMethodName = "/helloworld.v1.{{cookiecutter.module_name}}/SayHello"
)

// {{cookiecutter.module_name}}Client is the client API for {{cookiecutter.module_name}} service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type {{cookiecutter.module_name}}Client interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type {{cookiecutter.module_name}}Client struct {
	cc grpc.ClientConnInterface
}

func New{{cookiecutter.module_name}}Client(cc grpc.ClientConnInterface) {{cookiecutter.module_name}}Client {
	return &{{cookiecutter.module_name}}Client{cc}
}

func (c *{{cookiecutter.module_name}}Client) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, {{cookiecutter.module_name}}_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// {{cookiecutter.module_name}}Server is the server API for {{cookiecutter.module_name}} service.
// All implementations must embed Unimplemented{{cookiecutter.module_name}}Server
// for forward compatibility.
//
// The greeting service definition.
type {{cookiecutter.module_name}}Server interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplemented{{cookiecutter.module_name}}Server()
}

// Unimplemented{{cookiecutter.module_name}}Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type Unimplemented{{cookiecutter.module_name}}Server struct{}

func (Unimplemented{{cookiecutter.module_name}}Server) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (Unimplemented{{cookiecutter.module_name}}Server) mustEmbedUnimplemented{{cookiecutter.module_name}}Server() {}
func (Unimplemented{{cookiecutter.module_name}}Server) testEmbeddedByValue()                  {}

// Unsafe{{cookiecutter.module_name}}Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to {{cookiecutter.module_name}}Server will
// result in compilation errors.
type Unsafe{{cookiecutter.module_name}}Server interface {
	mustEmbedUnimplemented{{cookiecutter.module_name}}Server()
}

func Register{{cookiecutter.module_name}}Server(s grpc.ServiceRegistrar, srv {{cookiecutter.module_name}}Server) {
	// If the following call pancis, it indicates Unimplemented{{cookiecutter.module_name}}Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&{{cookiecutter.module_name}}_ServiceDesc, srv)
}

func _{{cookiecutter.module_name}}_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.({{cookiecutter.module_name}}Server).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: {{cookiecutter.module_name}}_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.({{cookiecutter.module_name}}Server).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// {{cookiecutter.module_name}}_ServiceDesc is the grpc.ServiceDesc for {{cookiecutter.module_name}} service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var {{cookiecutter.module_name}}_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.v1.{{cookiecutter.module_name}}",
	HandlerType: (*{{cookiecutter.module_name}}Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _{{cookiecutter.module_name}}_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "{{cookiecutter.module_name}}/v1/{{cookiecutter.module_name}}.proto",
}
