// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v6.30.2
// source: {{cookiecutter.module_name}}/v1/{{cookiecutter.module_name}}.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const Operation{{cookiecutter.module_name}}SayHello = "/helloworld.v1.{{cookiecutter.module_name}}/SayHello"

type {{cookiecutter.module_name}}HTTPServer interface {
	// SayHello Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

func Register{{cookiecutter.module_name}}HTTPServer(s *http.Server, srv {{cookiecutter.module_name}}HTTPServer) {
	r := s.Route("/")
	r.GET("/{{cookiecutter.module_name}}/{name}", _{{cookiecutter.module_name}}_SayHello0_HTTP_Handler(srv))
}

func _{{cookiecutter.module_name}}_SayHello0_HTTP_Handler(srv {{cookiecutter.module_name}}HTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HelloRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, Operation{{cookiecutter.module_name}}SayHello)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SayHello(ctx, req.(*HelloRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HelloReply)
		return ctx.Result(200, reply)
	}
}

type {{cookiecutter.module_name}}HTTPClient interface {
	SayHello(ctx context.Context, req *HelloRequest, opts ...http.CallOption) (rsp *HelloReply, err error)
}

type {{cookiecutter.module_name}}HTTPClientImpl struct {
	cc *http.Client
}

func New{{cookiecutter.module_name}}HTTPClient(client *http.Client) {{cookiecutter.module_name}}HTTPClient {
	return &{{cookiecutter.module_name}}HTTPClientImpl{client}
}

func (c *{{cookiecutter.module_name}}HTTPClientImpl) SayHello(ctx context.Context, in *HelloRequest, opts ...http.CallOption) (*HelloReply, error) {
	var out HelloReply
	pattern := "/{{cookiecutter.module_name}}/{name}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(Operation{{cookiecutter.module_name}}SayHello))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
